name: Playwright Cucumber Tests
on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        # Kluczowy moment: wchodzimy dok≈Çadnie tam, gdzie jest package.json
        working-directory: ./TypeScript/projekt
        run: npm install

      - name: Install Playwright Browsers
        working-directory: ./TypeScript/projekt
        run: npx playwright install --with-deps

      - name: Run Cucumber Tests
        working-directory: ./TypeScript/projekt
        run: npm test